# Generated by Django 3.0.8 on 2020-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('discrption', models.CharField(max_length=200)),
                ('price', models.SmallIntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
