# Generated by Django 3.0.8 on 2020-07-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_first', models.CharField(max_length=50)),
                ('receiver_last', models.CharField(max_length=50)),
                ('receiver_address', models.CharField(max_length=100)),
                ('receiver_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_country', models.CharField(max_length=20)),
                ('receiver_state', models.CharField(max_length=20)),
                ('receiver_zip', models.CharField(max_length=5)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Processing'), ('C', 'Completed'), ('D', 'Deleted')], default='P', max_length=1)),
                ('admin', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shopping.Order')),
                ('billing_first', models.CharField(max_length=50)),
                ('billing_last', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=100)),
                ('billing_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', models.CharField(max_length=20)),
                ('billing_state', models.CharField(max_length=20)),
                ('billing_zip', models.CharField(max_length=5)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('token_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Payment Sucess', 'Payment Sucess'), ('Order confirm', 'Order confirm'), ('Order complete', 'Order complete'), ('Order delete', 'Order delete'), ('Change order', 'Change order')], max_length=20)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('new_order_id', models.IntegerField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Order')),
            ],
        ),
    ]
