# Generated by Django 3.0.8 on 2020-07-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_log_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discrption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
