# Generated by Django 3.0.8 on 2020-07-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200713_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receiver_address2',
            new_name='receiver_addresstwo',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='billing_address2',
            new_name='billing_addresstwo',
        ),
    ]
